environments:
  local-docker:
    ENVIRONMENT: "local"
    DATABASE_URL: "postgresql+asyncpg://natodi-local:natodi-local@db:5432/natodi"
  local:
    ENVIRONMENT: "local"
    DATABASE_URL: "postgresql+asyncpg://natodi-local:natodi-local@localhost:5432/natodi"
  digitalocean:
    ENVIRONMENT: "digitalocean"
    DATABASE_URL: "secret"  # will be populated from env